### ISSUE TITLE
Can it support S9C?

### ISSUE THREAD

**Issue by d9394** [HrochL/CWSL#1]
Is the CWSL_TEE.DLL support S9C sdr receiver?

**Comment by HrochL** [comment]
CWSL_TEE suport all SDR's ... which have their own driver :-)
It adds itself between this driver and the skimmer. 
I personally have no experience with this SDR, but I found this driver for it http://www.rabbit-sdr.com/wp-content/uploads/2016/05/DLL.rar So it should work.

**Comment by d9394** [comment]
Roger, thanks
Let me going to try it.

**Comment by d9394** [comment]
After install ipp51 and vc, then I copy  Extio_CWSL.dll  into HDSDR  directory  and start HDSDR, after select this DLL, there are a message windows said : Can't find ipps-7.dll , and HDSDR can not load this dll to run.

**Comment by HrochL** [comment]
Mea culpa - i was upgrade compiler & libraries. Please try https://github.com/HrochL/CWSL/blob/master/bin/IPP70.zip

**Comment by d9394** [comment]
I had tried to unpack IPP70.zip into c:\windows\system32 and c:\windows\syswow64, HDSDR also can't work. 
But after I unpack IPP70.zip into HDSDR directory , the HDSDR works. That is great, now the skimmer and HDSDR can running together.
