### ISSUE TITLE
Can CWSL support LAN function?

### ISSUE THREAD

**Issue by d9394** [HrochL/CWSL#2]
![cwsl](https://user-images.githubusercontent.com/15172911/29953116-1c61fbf4-8f00-11e7-9f19-c617871727d4.png)
There are two computer : One is connected with SDR , another running skimmer or HDSDR to decode, and two computer is communite through a lan

**Comment by HrochL** [comment]
Currently there is no such option.

**Comment by d9394** [comment]
Roger
