### ISSUE TITLE
How can I using CW skimmer server and RTTY skimmer server with CWSL at same time?

### ISSUE THREAD

**Issue by d9394** [HrochL/CWSL#3]
I place CWSL_Tee.dll and CWSL_Tee.cfg into CW skimmer server directory and RTTY skimmer server directory, and then I startup CW skimmer server ,it is OK, but when I startup RTTY skimmer server ,it display SDR Fail
![qq 20170925183640](https://user-images.githubusercontent.com/15172911/30804594-9b665bc4-a220-11e7-8f70-6cc6e31d9fae.png)

**Comment by HrochL** [comment]
Try to folow this http://www.reversebeacon.net/downloads/aggregator/Running-RTTYSkimServer-and-CW-SkimServer.pdf

**Comment by d9394** [comment]
Roger, Thanks, two server now are running at same time.

**Comment by J69DSFrans** [comment]
I had the two skimmers working, had a pc crash. Now All what I try fails witht he same issue as mentioned by d9394.
The link mentioned is not available ...
Would somebody have the pdf with the solution to share

**Comment by fruehwi** [comment]
Me too.
This document http://www.reversebeacon.net/downloads/aggregator/Running-RTTYSkimServer-and-CW-SkimServer.pdf is not available anymore.
Is there a alternative download available ? 
73 Tom

**Comment by HrochL** [comment]
I don't know ... try asking the RBN why they removed the file
