### ISSUE TITLE
State Error C1083 Cannot open include file: 'ipp.h': No such file or directory Extio_CWSL ...

### ISSUE THREAD

**Issue by n1gp** [HrochL/CWSL#4]
Hi,
Trying to build your CWSL_Tee using VS 2017 and getting an error about ipp.h
Do I need to install the whole Intel development library/... or could I just get by
if ipp.h was included in your project?

EDIT: I am able to successfully build the CWSL_Tee.dll without the ipp.h, but it
doesn't seem to work if I replace your released CWSL_Tee.dll with my VS 2017 built CWSL_Tee.dll

Thanks

**Comment by HrochL** [comment]
Hi,
some of the CWSL modules don´t require IPP. CWSL_Tee.dll is one of them. But for example Extio_CWSL.dll requires it. The full development version of IPP libraries is required for its compilation.
Dependence on these libraries could be relatively easy to remove - I only use them for sample type conversion and over-sampling. Unfortunately, I still can not find the time for it.
I do not find any reason why CWSL_Tee build by you would not work. How exactly does it look like it does not work?

**Comment by n1gp** [comment]
When I first clicked on the solution in VS 2017 it asked me if I wanted to retargetbto the latest SDK (10.x) and from v140 to v141. First I chose to convert and CWSL_Tee.dll built fine. But when I run it in place of your built one it does nothing, no log, nothing in SkimSrv for an entry in devices.

If I start fresh and open the solution but choose not to update the project to the latest I get this when I try to build: Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8020	The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	CWSL_Tee	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets	57

**Comment by HrochL** [comment]
Unfortunately I have no experience with VS2017. So I can just look for something about this topic on the Internet :-)
A similar problem is solved here https://developercommunity.visualstudio.com/content/problem/48806/cant-find-v140-in-visual-studio-2017.html
Maybe you could try it too ...

**Comment by n1gp** [comment]
Thanks, that worked. And thanks for CWSL!
