### ISSUE TITLE
Enhancement to ExtIO_CWSL

### ISSUE THREAD

**Issue by Supremehamster** [HrochL/CWSL#8]
Hi,
Thanks for your excellent CWSL software.
Please may I have an enhancment to ExtIO_CWSL.dll (so that each hdsdr instance I run) has a .ini or param file or similar to select the default startup band(1-7 please)? 
That way I can use my QS1r sdr to auto-start without manually selecting the band from the ExtIO_CWSL.dll gui.
In other words a startup band in the ini file in each hdsdr folder?
Cheers,
Matt.

p.s. A scale factor startup default around 13 would be nice somewhere as well.

**Comment by takgr** [comment]
I had also the same requirement, in order to auto start one HDSDR instance for each band.
The quick way to solve this was to hard code the default band value of ExtIO and compile multiple binaries, each for every instance of HDSDR. It works for a few months now, but such a enhancement would be great!

**Comment by Supremehamster** [comment]
Any chance of hardcoding 7 bands for me? - I cant get it to compile on my visual studio...

**Comment by HrochL** [comment]
Hi,
we can get directory from which is the exe-file originated the process. In the same directory we can look for a file with the initial setup. There could be both the band number and the scale factor. 
Would that suit you?

**Comment by Supremehamster** [comment]
Ooooo Yes please :)

**Comment by HrochL** [comment]
So try the last version ... 
CWSL.zip now contains file Extio_CWSL.cfg. Copy it to HDSDR directory with the last version of Extio_CWSL.dll. On the first line in this file is band index and the second line can contain scale factor.

**Comment by Supremehamster** [comment]
Thanks -  copied in zip to afreet folder then copied dll and cfg to hdsdr but alas...
i got No h/w specific extio-dll found error ?
Skimmer Server 1.6
HDSDR v2.76
10.0.16299 OS (i5 cpu)
have rebooted and checked its there in hdsdr folder - again no go.

also, i reverted the dll back to an older (12k) version and all returns to normal.
so something to do with the new Extio_CWSL.dll?

**Comment by Supremehamster** [comment]
Got it working by installing IPP70 and vcredist from the bin directory 👍 
Wonderful!
Thanks for yours and your friend's excellent programming skills!
