### ISSUE TITLE
CWSL_USBWave Line VAC vs. WaveOutNr

### ISSUE THREAD

**Issue by Supremehamster** [HrochL/CWSL#9]
Hi all,
Thanks to Alex for his great CWSL_USBWave 👍 
Please can we go for 
Usage: CWSL_USBWave FreqHz LineNr Scale_factor
instead of
Usage: CWSL_USBWave FreqHz WaveOutNr Scale_factor
By LineNr I mean Line number for Virtual Audio Cable.
I know mine and others remap to a different WaveOutNr when you do other changes on the PC.
Thanks,
Matt.

**Comment by alexranaldi** [comment]
Hi Matt,
You can specify the name of the audio device as a string. For example, I rename my Virtual Audio cables.  I have 7 cables, one for each band.  In Control Panel, I rename them to:
"17m", "20m", "40m", etc.
In CWSL_USBWave, in place of the WaveOurNr, you can place a string in quotes with the name of the Virtual Audio cable.
Does that meet your need?
Alex

**Comment by Supremehamster** [comment]
Hi Alex,
That sounds ideal - thanks.
Matt.

**Comment by Supremehamster** [comment]
might have found a bug....
if i put in as target in shortcut
"C:\Program Files (x86)\Afreet\SkimSrv\CWSL_USBWave.exe" 3573000 "Line 2" 13
i get 
Using wave output device: 8 Line 26 (Virtual Audio Cable)
Oops.

**Comment by alexranaldi** [comment]
Uh oh!  Sounds like I have a string compare bug. I will take a look this evening!

**Comment by Supremehamster** [comment]
Got around it by making each VAC name uniquely different on first chracter e.g. a1 b3 c5 etc.
Now it works ok.
Thanks.

**Comment by d9394** [comment]
I has another idea: let the CWSL_USBWave(CWSL_SSBWave) program can streaming wave output with stdout pipe? 
then with the pipe I can use netcat to send the wave stream to another computer using network to do more interesting things : such as ft8&wspr decode; ffmpeg server to broadcast; websdr service
